### ISSUE TITLE
train dataset

### ISSUE THREAD

**Issue by xuanzhangyang** [jingliting/NTIRE2018#1]
hello, 你好，请问你有track 2、3、4的训练数据吗？比赛结束了，官方已经看不到数据集了。
你是不是用的edsr然后在track2的数据集上微调的？在real image上有效果吗？

**Comment by jingliting** [comment]
不好意思，最近在忙别的事情，没太关注git。我这里有track2,3,4的数据集，你可以从这里下载
链接: https://pan.baidu.com/s/1Fdc2HC7sK4Zp8zJgjXyYjg 密码: ptbf

**Comment by jingliting** [comment]
你说的real image指的是？我们有用celeba数据集上训练人脸图像的超分辨率，效果很好，根据你的具体应用场景，需要使用相关的数据集重新训练模型。
对于track2,3,4我们没有只使用edsr，因为降采样方式未知，用edsr（及其微调形式）在track2,3,4上并不能起到很好的效果，我们用了放大-缩小双网络的形式，同时需要考虑去噪，去模糊等更多具体的问题。

**Comment by xuanzhangyang** [comment]
后面我下载了你的track2,3,4数据集， 里面都是lr, 我用的gt是我以前下载的div2k里的gt， 然后我发现切块后， lr与gt有偏移，图像对不上， 你有遇到吗？

**Comment by jingliting** [comment]
是有偏移，比赛时官方发布的eval代码有做相应的调整
